require: rubocop-rspec

inherit_from:
  - https://raw.githubusercontent.com/trailblazer/meta/master/rubocop.yml

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Layout/LineLength:
  Enabled: false
